#!/bin/bash

# echo " __                 "
# echo "/ _\ __ _ _ __ ___  "
# echo "\ \ / _\` | '_ \` _ \ "
# echo "_\ \ (_| | | | | | |"
# echo "\__/\__,_|_| |_| |_|"

# echo "Be ambitous - and build new capabilities"
# echo "- We’re all figuring it out as we go! 🤓😉😌"
# echo ""
# echo "Remember, with childcare"
# echo "- pursue the best solution for all involved. Don't get hung up on the fairest"
# echo "- single-handed parenting may sometimes actually be simpler, easier"

echo "- 👷 Be a BUILDER. Be ambitious, and build new capabilities"
echo "- 🤝 Delegate. Especially glue work. To Product, to Design, to other engineers"
echo "- 💪 Take risks. Dive in"
echo "- 💖 Love the subject - don't fear it"
echo "- 🕒 Take the time you need"
echo "- 📚 Go back and solidify my learnings"
echo ""
echo "- NEVER give feedback that was autogenerated and wasn't filtered by my own judgement"
echo ""
echo "And finally ENJOY YOUR WORK. And 'Don't give too many fucks'"
echo "👋 Keep smiling, and fake it til you make it 😉"

# # Allow [ or ] whereever you want
# unsetopt nomatch
